# Generated by Django 4.2 on 2023-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="Programing", max_length=20),
            preserve_default=False,
        ),
    ]
